### ISSUE TITLE
Which open source license is SciHive under?

### ISSUE THREAD

**Issue by andrewhead** [ranihorev/scihive-frontend#2]
Hi @ranihorev! Thanks for developing SciHive, what a cool tool! :-)

I'm thinking of reusing some of SciHive's components (PDF processing code, parts of the PDF viewer UI) for a research project. The [SciHive about page](https://www.scihive.org/about) mentions that the project is open source. Is the source code released under a specific license (e.g., MIT, BSD, etc.)? Just wondering if the open source license permissive enough for me to build on the code in my specific case.

**Comment by ranihorev** [comment]
Thanks!
We haven't given that much thought, but I believe that we can adopt the MIT
license.

Feel free to use the code. PRs are welcomed of course :)

**Comment by ranihorev** [comment]
Please note that some of the ui is based on react-pdf-highlighter

**Comment by andrewhead** [comment]
Wonderful, thank you! And I'll keep that in mind about the PRs :-)
