### ISSUE TITLE
Real-time update of UI

### ISSUE THREAD

**Issue by freeman42x** [ranihorev/scihive-frontend#9]
When a peer reviewer adds a comment or highlight it would be very good for the user experience if the user interface would automatically refresh to show any newly added comment or highlight.

A friend had a look at the code and he said that a change like:

```js
setInterval(() => fetchComments(paperId), 1000)
```

at this line:

https://github.com/ranihorev/scihive-frontend/blob/14791f591a60d76a2c6dee04f97912c3fe6a9b3a/src/stores/paper.ts#L265

should be sufficient to make it update in real-time.

Above method is using polling so if you would want a more efficient and closer to real-time implementation you would want to use WebSockets and that requires server-side changes.

**Comment by puffnfresh** [comment]
1 second is probably too high of a load, but I just tested the change (with 60 seconds instead) and it works great.

**Comment by freeman42x** [comment]
@puffnfresh I guess it depends on how many users are using the site at the same time. But setting it to 60 seconds seems way too much. maybe 5 seconds? 10?

Ideal option would be to do this using WebSockets.

**Comment by ranihorev** [comment]
We can add the polling mechanism easily, it's a bit hacky but much faster to implement.
In addition, we're re-building the backend and switching to postgres. We can consider adding WebSockets after that.

**Comment by freeman42x** [comment]
@ranihorev If you could add polling with some sensibly low polling time that your servers can handle that would be very useful. And if you could add web sockets that would be so good!

**Comment by freeman42x** [comment]
@ranihorev me and @puffnfresh were testing the SciHive and I was really expecting it will be a real-time collaboration tool based on impression the site gave me.

**Comment by freeman42x** [comment]
Wrong conclusion on my part, on 2nd read there is no mention of real-time functionality here: https://start.scihive.org/

**Comment by ranihorev** [comment]
It’s something you can expect from a service such as SciHive :)
We’ll add that functionality soon, and you’re also welcome to open a PR if
you'd like.

**Comment by freeman42x** [comment]
> It’s something you can expect from a service such as SciHive :)

Exactly I was expecting it to work like Google Docs products with real-time sync. There is no reason not to implement that in current age. We had the tech to do that for a long time ago.

> We’ll add that functionality soon

Thank is awesome, thank you so much!

> and you’re also welcome to open a PR if you'd like.

I will consider that for the future, I am very busy with my own projects.

**Comment by ranihorev** [comment]
It took some time but we now support real-time updates for comments :)
